#
#server:
#  port: 8081
#
#spring:
#  main:
#    allow-bean-definition-overriding: true
#
#
#  shardingsphere:
#    # 参数配置，显示 sql
#    props:
#      sql:
#        show: true
#    # 配置数据源
#    datasource:
#      # 给每个数据源取别名，下面的 ds1,ds2,ds3 任意取名字
#      names: ds1,ds2,ds3
#      # 给master-ds1 每个数据源配置数据库连接信息
#      ds1:
#        # 配置druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://121.196.98.74:3306/order_test?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: root
#        password: 123456
#        maxPoolSize: 100
#        minPoolSize: 5
#      # 配置 ds2-slave
#      ds2:
#        # 配置druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://192.168.98.135:3306/order_test?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: root
#        password: 123456
#        maxPoolSize: 100
#        minPoolSize: 5
#      # 配置 ds3-slave
#      ds3:
#        # 配置druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://192.168.98.135:3306/order_test?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: root
#        password: 123456
#        maxPoolSize: 100
#        minPoolSize: 5
#      # 配置默认数据源 ds1
#    sharding:
#      # 默认数据源，主要用于写，注意一定要配置读写分离，注意：如果不配置，那么就会把三个节点都当做slave节点，新增、修改、删除会出错
#      default-data-source-name: ds1
#      # 配置数据源的读写分离，但是数据库一定要做主从复制
#    masterslave:
#      # 配置主从名称
#      name: ms
#      # 配置主库master，负责数据的写入
#      master-data-source-name: ds1
#      # 配置从库slave节点
#      slave-data-source-names: ds2,ds3
#      # 配置slave节点的负载均衡策略，采用轮询机制
#      load-balance-algorithm-type: round_robin
#
#
#
